#
#	settings.yaml contains the setting definitions in a nice human-readable format
#

enabled:
  title: Enable Protection
  type: checkbox
  default: on
  section_title: General Settings

password:
  title: Password
  type: password
  default: password

text:
  title: Text test
  type: text
  default: this is a test

login_duration:
  title: How long before a user's session expires
  type: text
  default: 86400 # one day
  section: advanced
  section_title: Advanced Settings